.PHONY: all clean copy

all: demo_df.dll demo_date.dll demo_time.dll demo_str.dll demo_list.dll demo_matrix.dll copy

%.dll: %.cpp
	R CMD SHLIB $<

# strangely, "R CMD build --binary rcppbind" won't copy the dll's to the installation file
# do so manually...
# config problem or R system problem?
copy: demo_df.dll demo_date.dll demo_time.dll demo_str.dll demo_list.dll demo_matrix.dll
	mkdir -p ../inst/libs
	cp *.dll ../inst/libs

clean:
	rm -f *.o *.d *.rc *.dll
